input {
  tcp {
    port => 5044
    codec => json
  }
}

filter {
  mutate {
    add_field => { "source" => "attacker_simulation" }
  }
}

output {
  stdout { codec => rubydebug }

  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "siem-events"
  }
}